# Michelin Rated Restaurants

In [1]:
import pandas as pd

## Initial Exploration & Preparation of Data

In [8]:
michelin = pd.read_csv("../../Michelin/michelin_data_2022.csv")
michelin.head(10)

,Name,Address,Location,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award
0,Aqua,"Parkstraße 1, Wolfsburg, 38440, Germany",Wolfsburg,225,225,EUR,"Creative, Modern Cuisine",10.789999,52.433172,+495361606056,https://guide.michelin.com/en/niedersachsen/wo...,http://www.restaurant-aqua.com,3 MICHELIN Stars
1,The Table Kevin Fehling,"Shanghaiallee 15, Hamburg, 20457, Germany",Hamburg,230,230,EUR,Creative,10.002980,53.542623,+494022867422,https://guide.michelin.com/en/hamburg-region/h...,http://www.the-table-hamburg.de/,3 MICHELIN Stars
2,Restaurant Überfahrt Christian Jürgens,"Überfahrtstraße 10, Rottach-Egern, 83700, Germany",Rottach-Egern,259,319,EUR,Creative,11.758229,47.696685,+4980226690,https://guide.michelin.com/en/bayern/rottach-e...,http://www.althoffcollection.com,3 MICHELIN Stars
3,Victor's Fine Dining by christian bau,"Schlossstraße 27, Perl, 66706, Germany",Perl,205,295,EUR,Creative,6.387211,49.535173,+49686679118,https://guide.michelin.com/en/saarland/perl/re...,https://www.victors-fine-dining.de/,3 MICHELIN Stars
4,Rutz,"Chausseestraße 8, Berlin, 10115, Germany",Berlin,198,245,EUR,"Modern Cuisine, Creative",13.386087,52.528351,+493024628760,https://guide.michelin.com/en/berlin-region/be...,https://www.rutz-restaurant.de/,3 MICHELIN Stars
5,Restaurant Bareiss,"Hermine-Bareiss-Weg 1, Baiersbronn, 72270, Ger...",Baiersbronn,150,335,EUR,Classic French,8.326988,48.520584,+497442470,https://guide.michelin.com/en/baden-wurttember...,http://www.bareiss.com,3 MICHELIN Stars
6,temporaire - Schwarzwaldstube,"Tonbachstraße 237, Baiersbronn, 72270, Germany",Baiersbronn,215,265,EUR,"Classic French, Creative",8.359063,48.536153,+4974424920,https://guide.michelin.com/en/baden-wurttember...,https://www.traube-tonbach.de/restaurants-bar/...,3 MICHELIN Stars
7,schanz. restaurant.,"Bahnhofstraße 8a, Piesport, 54498, Germany",Piesport,115,178,EUR,"Modern French, Creative",6.926600,49.877600,+49650792520,https://guide.michelin.com/en/rheinland-pfalz/...,http://www.schanz-restaurant.de,3 MICHELIN Stars
8,Waldhotel Sonnora,"Auf'm Eichelfeld 1, Dreis, 54518, Germany",Dreis,225,249,EUR,Classic French,6.810934,49.937732,+49657898220,https://guide.michelin.com/en/rheinland-pfalz/...,http://www.hotel-sonnora.de,3 MICHELIN Stars
9,L'Enclume,"Cavendish Street, Cartmel, LA11 6PZ, United Ki...",Cartmel,79,175,GBP,Creative,-2.953857,54.201725,+441539536362,https://guide.michelin.com/en/cumbria/cartmel/...,http://www.lenclume.co.uk,3 MICHELIN Stars

In [9]:
print(f"Columns:\n{michelin.columns.to_list()}")

Columns:
['Name', 'Address', 'Location', 'MinPrice', 'MaxPrice', 'Currency', 'Cuisine', 'Longitude', 'Latitude', 'PhoneNumber', 'Url', 'WebsiteUrl', 'Award']

We aim to plot the coordinates on a map and search for population density correlation and compare UK and France.

We drop `Url`, `PhoneNumber` and `FacilitiesAndService`. `Url` could perhaps become useful

In [10]:
michelin = michelin[['Name', 'Address', 'Location', 'MaxPrice', 'Currency', 'Cuisine', 'WebsiteUrl', 'Award', 'Longitude', 'Latitude']]
michelin.head()

,Name,Address,Location,MaxPrice,Currency,Cuisine,WebsiteUrl,Award,Longitude,Latitude
0,Aqua,"Parkstraße 1, Wolfsburg, 38440, Germany",Wolfsburg,225,EUR,"Creative, Modern Cuisine",http://www.restaurant-aqua.com,3 MICHELIN Stars,10.789999,52.433172
1,The Table Kevin Fehling,"Shanghaiallee 15, Hamburg, 20457, Germany",Hamburg,230,EUR,Creative,http://www.the-table-hamburg.de/,3 MICHELIN Stars,10.002980,53.542623
2,Restaurant Überfahrt Christian Jürgens,"Überfahrtstraße 10, Rottach-Egern, 83700, Germany",Rottach-Egern,319,EUR,Creative,http://www.althoffcollection.com,3 MICHELIN Stars,11.758229,47.696685
3,Victor's Fine Dining by christian bau,"Schlossstraße 27, Perl, 66706, Germany",Perl,295,EUR,Creative,https://www.victors-fine-dining.de/,3 MICHELIN Stars,6.387211,49.535173
4,Rutz,"Chausseestraße 8, Berlin, 10115, Germany",Berlin,245,EUR,"Modern Cuisine, Creative",https://www.rutz-restaurant.de/,3 MICHELIN Stars,13.386087,52.528351

In [11]:
# Columns are converted to lowercase for convenience
michelin.columns = michelin.columns.str.lower()

In [13]:
michelin.rename({'websiteurl': 'url', 'maxprice': 'price'}, axis=1, inplace=True)
print(f"Columns:\n{michelin.columns.tolist()}")

Columns:
['name', 'address', 'location', 'price', 'currency', 'cuisine', 'url', 'award', 'longitude', 'latitude']

In [14]:
michelin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6502 entries, 0 to 6501
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       6502 non-null   object
 1   address    6502 non-null   object
 2   location   6502 non-null   object
 3   price      6501 non-null   object
 4   currency   6501 non-null   object
 5   cuisine    6502 non-null   object
 6   url        5375 non-null   object
 7   award      6502 non-null   object
 8   longitude  6188 non-null   float64
 9   latitude   6188 non-null   float64
dtypes: float64(2), object(8)
memory usage: 508.1+ KB

There exist missing values which will be dealt with once partitioned by location

Range of values for specific columns

In [8]:
ignore = ['longitude', 'latitude', 'url', 'cuisine']

for column in michelin:
    if column in ignore:
        pass
    else:
        print(f"\nUnique {column}s: {michelin[column].unique()}\nTotal Unique: {len(michelin[column].unique())} values")

Unique names: ['noma' 'Maaemo' 'Frantzén' ... 'Zazie' 'Butchery & Wine' 'alewino']
Total Unique: 6687 values

Unique addresss: ['Refshalevej 96, Copenhagen, 1432 K, Denmark'
 'Dronning Eufemias gate 23, Oslo, 0194, Norway'
 'Klara Norra Kyrkogata 26, Stockholm, 111 22, Sweden' ...
 'ul. Józefa 34, Cracow, 32 056, Poland'
 'ul. Żurawia 22, Warsaw, 00 515, Poland'
 'ul. Mokotowska 48, Warsaw, 00 543, Poland']
Total Unique: 6706 values

Unique locations: ['Copenhagen, Denmark' 'Oslo, Norway' 'Stockholm, Sweden' ...
 'Almuñécar, Spain' 'Vitoria-Gasteiz, Spain' 'Warsaw, Poland']
Total Unique: 2645 values

Unique prices: ['€€€€' '$$$$' '$$$' '££££' '¥¥¥' '¥¥¥¥' '₩₩₩₩' '$$' '€€€' '¥¥' '฿฿฿฿'
 '₺₺₺₺' nan '€€' '₫₫' '₫₫₫₫' '£££' '££' '฿฿฿' '฿฿' '¥' '₩₩₩' '₺₺' '₺₺₺'
 '$' '€' '₫' '£' '฿' '₩' '₩₩' '₺']
Total Unique: 32 values

Unique awards: ['3 MICHELIN Stars' '2 MICHELIN Stars' '1 MICHELIN Star' 'Bib Gourmand']
Total Unique: 4 values

----
&nbsp;
## Separate `location` column

- `country` column. eg, 'USA'
- `city` column. eg, 'San Fransisco'

`location` is comma separated "country, city"

In [15]:
# Are there non-comma separated entries in `location`?
no_comma = michelin[~michelin['location'].str.contains(',')]
no_comma['location'].unique().tolist()

['Wolfsburg',
 'Hamburg',
 'Rottach-Egern',
 'Perl',
 'Berlin',
 'Baiersbronn',
 'Piesport',
 'Dreis',
 'Cartmel',
 'Bray',
 'London',
 'Vienna',
 'Beijing',
 'Macau',
 'Hong Kong',
 'Larrabetzu',
 'Lasarte - Oria',
 'El Puerto de Santa María',
 'Girona',
 'Dénia',
 'Villaverde de Pontones',
 'Madrid',
 'Donostia / San Sebastián',
 'Barcelona',
 'Tokyo',
 'SEOUL',
 'Runate',
 'Rubano',
 'Castel di Sangro',
 'Modena',
 'Brusaporto',
 'San Cassiano',
 'Milan',
 'Florence',
 'Alba',
 'Senigallia',
 'Rome',
 'Shanghai',
 'Osaka',
 'Kyoto',
 'Yountville',
 'Healdsburg',
 'Los Gatos',
 'San Francisco',
 'Stockholm',
 'Oslo',
 'Copenhagen',
 'Singapore',
 'Taipei',
 'New York',
 'Chicago',
 'Washington',
 'Kruiningen',
 'Zwolle',
 'Crissier',
 'Basel',
 'Fürstenau',
 'Monaco',
 'Reims',
 'Eugénie-les-Bains',
 'Vonnas',
 'Saint-Tropez',
 'Menton',
 'Saint-Martin-de-Belleville',
 'Paris',
 'Courchevel',
 'Marseille',
 'Valence',
 'Ouches',
 'Le Castellet',
 'Chagny',
 'Megève',
 'Fontjoncouse',
 'Les Baux-de-Provence',
 'La Rochelle',
 'Saint-Bonnet-le-Froid',
 'Annecy',
 'Antwerpen',
 'Kruishoutem',
 'Donaueschingen',
 'Grassau',
 'Krün',
 'Munich',
 'Mannheim',
 'Leipzig',
 'Rantum',
 'Neunburg vorm Wald',
 'Nuremberg',
 'Bad Neuenahr-Ahrweiler',
 'Aschau im Chiemgau',
 'Bergisch Gladbach',
 'Stuttgart',
 'Dorsten',
 'Hanover',
 'Augsburg',
 'Bad Peterstal',
 'Cologne',
 'Saarlouis',
 'Constance',
 'Frankfurt on the Main',
 'Fellbach',
 'Wirsberg',
 'Rust',
 'Saarbrücken',
 'Sulzburg',
 'Zweiflingen',
 'Glücksburg',
 'Andernach',
 'Wangels',
 'Blackrock',
 'Celbridge',
 'Dublin City',
 'Machynlleth',
 'Summerhouse',
 'Auchterarder',
 'Great Milton',
 'Nottingham',
 'Cambridge',
 'Aughton',
 'Marlow',
 'Salzburg',
 'Chengdu',
 'Bangkok',
 'Leça da Palmeira',
 'Porches',
 'Vila Nova de Gaia',
 'Funchal',
 'Albufeira',
 'Lisbon',
 'Urdaitz',
 'La Salgar',
 'El Palmar',
 'Almansa',
 'Xàbia',
 'Olot',
 'Guía de Isora',
 'Canyamel',
 'Errenteria',
 'O Grove',
 'Corçà',
 'Llançà',
 'Ronda',
 'Ezcaray',
 'Cocentaina',
 'Toledo',
 'Cáceres',
 'Valencia',
 'Córdoba',
 'Marbella',
 'Godia',
 'Ischia',
 'Tirol',
 'Lonigo',
 'Licata',
 'Rivodutri',
 'Orta San Giulio',
 'Brusciano',
 'Montemerano',
 'Marina del Cantone',
 'Lughetto',
 'Anacapri',
 'Telese',
 "Sant' Agata sui Due Golfi",
 'Trieste',
 "Colle di Val d'Elsa",
 'Ragusa',
 'Guarene',
 'Concesio',
 'Cervere',
 'Cornaredo',
 'Gargnano',
 'Ghirlanda',
 'Vico Equense',
 'Fondotoce',
 'Cesenatico',
 'Viareggio',
 'Mauls',
 'Imola',
 'Paestum',
 'Sarentino',
 'Marzocca',
 'Venice',
 'Verona',
 'Athens',
 'Elk',
 'Culver City',
 'Hollywood',
 'West Hollywood',
 'San Diego',
 'Oakland',
 'Santa Monica',
 'Los Angeles',
 'Kobarid',
 'Guangzhou',
 'Malmo',
 'Stavanger',
 'Leynavatn',
 'Henne',
 'Taichung',
 'Tarrytown',
 'Roermond',
 'Harderwijk',
 'Giethoorn',
 'Amsterdam',
 'Amstelveen',
 'Waalre',
 'Reijmerstok',
 'Cadzand-Bad',
 'Nuenen',
 'Heeze',
 'Rotterdam',
 'Hoofdplaat',
 'Overveen',
 'Staphorst',
 'Le Noirmont',
 'Saint Moritz',
 'Vitznau',
 'Ascona',
 'Lausanne',
 'Wigoltingen',
 'Sankt Gallen',
 'Vals',
 'Satigny',
 'Zurich',
 'Heiden',
 'Schwyz',
 'Bad Ragaz',
 'Steinen',
 'Küsnacht',
 'Lembach',
 'Kaysersberg',
 'Talloires-Montmin',
 'Vienne',
 'Chaudes-Aigues',
 'Saint-Amour-Bellevue',
 'Saulieu',
 'Manigod',
 'Onzain',
 'Garons',
 'Saint-Emilion',
 'Clermont-Ferrand',
 'Joigny',
 'Le Cannet',
 "Collonges-au-Mont-d'Or",
 'Lyon',
 'Bordeaux',
 "L'Herbaudière",
 'La Turbie',
 'Jongieux',
 'Magescq',
 'La Plaine-sur-Mer',
 'Busnes',
 'Pujaudran',
 'Granges-les-Beaumont',
 'Wingen-sur-Moder',
 'Colmar',
 'La Madelaine-sous-Montreuil',
 'Porto-Vecchio',
 'Narbonne',
 'Obernai',
 'Toulouse',
 'Cannes',
 'Le Havre',
 'Cancale',
 "Val-d'Isère",
 'Veyrier-du-Lac',
 'Cassis',
 'Pyla-sur-Mer',
 'Illhaeusern',
 'Dijon',
 'Laubach',
 'Plomodiern',
 'Arbois',
 'Laguiole',
 'Ramatuelle',
 'Carcassonne',
 'Èze',
 'Montlivault',
 'Martillac',
 'Uriage-les-Bains',
 'Nice',
 'Oetrange',
 'Woluwe-Saint-Pierre',
 'Sint-Kruis',
 'Baudour',
 'Arbre',
 'De Panne',
 'Duffel',
 'Izegem',
 'Liernu',
 'Uccle',
 'Heist',
 'Gent',
 'Neerharen',
 'Our',
 'Brussels',
 'Roeselare',
 'Opglabbeek',
 'Elverdinge',
 'Beveren-Leie',
 'Reet',
 'Ellezelles',
 'Lommel',
 'Anderlecht',
 'São Paulo',
 'Rio de Janeiro',
 'Halle (saale)',
 'Regensburg',
 'Berchtesgaden',
 'Schluchsee',
 'Wernigerode',
 'Efringen-Kirchen',
 'Dortmund',
 'Bad Tölz',
 'Münster',
 'Duggendorf',
 'Lindau',
 'Heringsdorf',
 'Kiedrich',
 'Timmendorfer Strand',
 'Bodman-Ludwigshafen',
 'Wuppertal',
 'Erkelenz',
 'Darmstadt',
 'Frasdorf',
 'Bad Hersfeld',
 'Salach',
 'Niederkassel',
 'Hohenkammer',
 'Waldenbuch',
 'Kirchheim an der Weinstraße',
 'Langenzenn',
 'Friedland',
 'Heidesheim am Rhein',
 'Deidesheim',
 'Waiblingen',
 'Neupotz',
 'Fulda',
 'Bad Doberan',
 'Düsseldorf',
 'Endingen am Kaiserstuhl',
 'Ulm',
 'Darscheid',
 'Sonnenbühl',
 'Sommerhausen',
 'Koblenz',
 'Lahr',
 'Velbert',
 'Kernen im Remstal',
 'Odenthal',
 'Nideggen',
 'Aachen',
 'Flensburg',
 'Pfronten',
 'Wyk',
 'Langenau',
 'Niederwinkling',
 'Radebeul',
 'Pirmasens',
 'Gernsbach',
 'Baden-Baden',
 'Lübeck',
 'Waldbronn',
 'Würzburg',
 'Aerzen',
 'Panker',
 'Heidelberg',
 'Gummersbach',
 'Feldberger Seenlandschaft',
 'Ostseebad Binz',
 'Essen',
 'Euskirchen',
 'Illschwang',
 'Cuxhaven',
 'Perasdorf',
 'Tinnum',
 'Paderborn',
 'Ehningen',
 'Kirchdorf',
 'Vogtsburg im Kaiserstuhl',
 'Bad Säckingen',
 'Stolpe',
 'Dresden',
 'Auerbach in der Oberpfalz',
 'Neuleiningen',
 'Wiesbaden',
 'Herleshausen',
 'Haltern am See',
 'Bietigheim-Bissingen',
 'Ofterschwang',
 'Oberstdorf',
 'Weikersheim',
 'Trier',
 'Volkach',
 'Pulheim',
 'Duisburg',
 'Blieskastel',
 'Vaihingen an der Enz',
 'Trittenheim',
 'Öhningen',
 'Sankt Wendel',
 'Kerpen',
 'Naurath/Wald',
 'Bad Kötzing',
 'Selzen',
 'Dierhagen',
 'Bad Sobernheim',
 'Amtzell',
 'Krakow am See',
 'Rostock',
 'Wachenheim an der Weinstraße',
 'Limburg an der Lahn',
 'Starnberg',
 'Asperg',
 'Ettlingen',
 'Grenzach-Wyhlen',
 'Bad Krozingen',
 'Osnabrück',
 'Rheda-Wiedenbrück',
 'Werder',
 'Potsdam',
 'Karlsruhe',
 'Schirgiswalde-Kirschau',
 'Teisnach',
 'Mainz',
 'Moos bei Deggendorf',
 'Waldkirchen',
 'Kiel',
 'Bonn',
 'Bad Zwischenahn',
 'Schmallenberg',
 'Neuhütten',
 'Weisenheim am Berg',
 'Rötz',
 'Langenargen',
 'Meerbusch',
 'Eltville am Rhein',
 'Horben',
 'Dermbach',
 'Meersburg',
 'Herrenberg',
 'Neuhausen',
 'Uhingen',
 'Tuttlingen',
 'Schwäbisch Hall',
 'Mittenwald',
 'Königsbronn',
 'Weingarten',
 'Wallerfangen',
 'Neustadt an der Weinstraße',
 'Xanten',
 'Scharbeutz',
 'Frankenberg',
 'Hörnum',
 'Detmold',
 'Bad Kissingen',
 'Nördlingen',
 'Bad Teinach-Zavelstein',
 'Schorndorf',
 'Norderney',
 'Pleiskirchen',
 'Balzan',
 'Valletta',
 'Mdina',
 'Ballydehob',
 'Ardmore',
 'Baltimore',
 'Adare',
 'Kilkenny',
 'Cork',
 'Thomastown',
 'Kinsale',
 'Galway',
 'Lisdoonvarna',
 'Hunstanton',
 'Anstruther',
 'Menai Bridge',
 'Lympstone',
 'Whitebrook',
 'Lower Beeding',
 'Ripley',
 'Horsham',
 'Egham',
 'Wall',
 'Holt',
 'Bridge',
 'Dorking',
 'Seasalter',
 'Morston',
 'Fence',
 'Castle Combe',
 'Murcott',
 'Birkenhead',
 'Whatcote',
 'South Dalton',
 'Mountsorrel',
 'Hambleton',
 'Ilfracombe',
 'Malmesbury',
 'Askham',
 'Peat Inn',
 'Colerne',
 'Skelton',
 'Bagshot',
 'Aberystwyth',
 'Oldstead',
 'Hetton',
 'Tenbury Wells',
 'Fordwich',
 'Saltwood',
 'Bury St Edmunds',
 'Stratford-on-Avon',
 'Winteringham',
 'Ripon',
 'Braithwaite',
 'Langho',
 'East Wallhouses',
 'Torquay',
 'St Helier',
 'Broadstairs',
 'Bowness-on-Windermere',
 'Knowstone',
 'Port Isaac',
 'Harome',
 'Llanddewi Skirrid',
 'Grasmere',
 'Penarth',
 'Isle of Skye',
 'Newbury',
 'Hampton in Arden',
 'Lichfield',
 'Amersham',
 'East Grinstead',
 'Leith',
 'Oxwich',
 'Bath',
 'Ascot',
 'Manchester',
 'York',
 'Padstow',
 'Birmingham',
 'Newcastle Upon Tyne',
 'Ambleside',
 'Leeds',
 'Belfast',
 'Glasgow City',
 'Edinburgh',
 'Crieff',
 'Cheltenham',
 'City of Bristol',
 'Bruton',
 'Kenilworth',
 'Nonthaburi',
 'Phuket',
 'Soldeu',
 'Passos de Silgueiros',
 'Amarante',
 'Lagoa',
 'Portimao',
 'Vila Nova de Cacela',
 'Bragança',
 'Praia do Guincho',
 'Reguengos de Monsaraz',
 'Guimaraes',
 'Sintra',
 'Porto',
 'Almancil',
 'Lagos',
 'Tavira',
 'Cercs',
 'Gombrèn',
 'Anglès',
 'San Salvador de Poio',
 'El Masnou',
 'Galdakao',
 'Benavente',
 'Santa Comba',
 'Esquedas',
 'Arriondas',
 'Ponferrada',
 'Quintanilla de Onésimo',
 'Illescas',
 'Tramacastilla',
 "Port d'Alcúdia",
 'Arguineguín',
 'la Nucía',
 'Cornudella de Montsant',
 'Sagunt',
 'Axpe',
 'Bellvís',
 'Ulldecona',
 'Hoznayo',
 'Ainsa',
 'Salinas',
 'Ondara',
 'Tossa de Mar',
 'Sant Fruitós de Bages',
 'Novo Sancti Petri',
 'Santa Coloma de Gramenet',
 'Salou',
 'Elciego',
 'Palma de Mallorca',
 'Arbúcies',
 'Daroca de Rioja',
 'Pereiro de Aguiar',
 'Amorebieta - Etxano',
 'Alcossebre',
 'La Vall de Bianya',
 'Getaria',
 'Sóller',
 'Peralada',
 'Sigüenza',
 'Valdemoro',
 'Huesca',
 "Vall d'Alba",
 "Castelló d'Empúries",
 'Barizo',
 'Capdepera',
 'Sagàs',
 'Elche',
 'Sardón de Duero',
 'Soria',
 'Cartagena',
 'Oiartzun',
 'Dima',
 'Benicarló',
 'Peñafiel',
 'Gimenells',
 'Puente Arce',
 'Zarza de Granadilla',
 'Salamanca',
 'Sant Antoni de Portmany',
 'Castroverde de Campos',
 'Ampuero',
 'Hondarribia',
 'Torrenueva',
 'Llanes',
 'Talavera de la Reina',
 'Navaleno',
 'Calp',
 'Calldetenes',
 'El Ejido',
 'Xerta',
 'Malaga',
 'Cuenca',
 'Pontevedra',
 'Olost',
 'Miranda de Ebro',
 'Ribadesella',
 'Adeje',
 'Bilbao',
 'Puerto de Mogán',
 'Serpe',
 'Matapozuelos',
 'Llagostera',
 'Seville',
 'Prendes',
 'Santiago de Compostela',
 'Alacant',
 'Jaén',
 'Pamplona',
 'Fuengirola',
 'Eivissa',
 'Cambrils',
 'Sort',
 'Logrono',
 'A Coruña',
 'Torre de Juan Abad',
 'Murcia',
 'Palmanova',
 'Palma',
 'Valladolid',
 'Saragossa',
 'Las Palmas de Gran Canaria',
 'Ourense',
 'Cambados',
 'Haro',
 'Gijón',
 'Santander',
 'Leon',
 'Vigo',
 'Jerez de la Frontera',
 'San Marino',
 'Bacoli',
 "San Paolo d'Argon",
 'Caluso',
 'Oggiono',
 'San Piero a Sieve',
 'Acuto',
 'Chiusdino',
 'Bergeggi',
 'San Piero in Bagno',
 'Montepagano',
 'Malo',
 'Albavilla',
 'Cavaion Veronese',
 'Molini',
 'Viterbo',
 'Chiusi',
 'Stradella',
 'Archi',
 'Vernante',
 'Pontelongo',
 'Conversano',
 'Ortisei',
 'Savelletri',
 'Seggiano',
 'Rubbianino',
 'Arzignano',
 'Schio',
 'Roverchiara',
 'Terracina',
 'Porto Ercole',
 'Mantello',
 'Bagheria',
 'Somma Vesuviana',
 'Altissimo',
 'Fasano del Garda',
 'Ravina',
 'Passignano',
 'Barbarano Vicentino',
 'Marina di Gioiosa Ionica',
 'Castelbello',
 'Codigoro',
 'Torre del Greco',
 'Pollone',
 "Puos d'Alpago",
 "Santa Cristina d'Aspromonte",
 'San Teodoro',
 'Laveno',
 'San Salvo Marina',
 'San Martino',
 'Bellagio',
 'Soprabolzano',
 'Canale',
 'Castellammare di Stabia',
 'Castel Maggiore',
 'Oderzo',
 'Terrasini',
 'Vallesaccarda',
 'Marina di Pietrasanta',
 'Trescore Balneario',
 'Arco',
 'Ruda',
 'Carpaneto Piacentino',
 'Porto San Giorgio',
 'Conca dei Marini',
 'Malcesine',
 'Labico',
 'Madonna di Campiglio',
 'Marina di Grosseto',
 'Tigliole',
 'Sorisole',
 'Desenzano del Garda',
 'Savigno',
 'Fiumicino',
 'San Gimignano',
 'Villa di Chiavenna',
 'Merano',
 'Treiso',
 'Salina',
 'Bardolino',
 'Nova Levante',
 "Serralunga d'Alba",
 'Pralboino',
 'Arezzo',
 'Gaiole in Chianti',
 'Toblach',
 "Campione d'Italia",
 'Sirmione',
 'Eboli',
 'Marina di Bibbona',
 'Domodossola',
 'Trevinano',
 'San Maurizio Canavese',
 'Venaria Reale',
 'Nola',
 'Borgonato',
 'Isola di Capo Rizzuto',
 'Lamezia Terme',
 'Torre del Mangano',
 'Isola Vulcano',
 'Almè',
 'Maiori',
 'Loreto',
 'Rovereto',
 'Vigevano',
 'Priocca',
 'Baia Sardinia',
 'Cioccaro',
 'Pula',
 'Tisens',
 'Pudiano',
 'Perugia',
 'Moena',
 'Palermo',
 'Castelfranco Veneto',
 'Vicenza',
 "Piobesi d'Alba",
 'Spinetta Marengo',
 'Guardiagrele',
 'Cormons',
 'Putignano',
 'Cernobbio',
 'Cavi di Lavagna',
 'Taormina',
 'Courmayeur',
 'San Casciano dei Bagni',
 'Madesimo',
 'Treviglio',
 'Torriana',
 'Vitorchiano',
 'Alassio',
 'Caltagirone',
 'Linguaglossa',
 'Calvisano',
 'San Remo',
 'Manerba del Garda',
 'La Morra',
 'San Michele',
 'Peschici',
 'Borgoricco',
 'Imperia',
 'Sappada',
 'Soriso',
 'Poggio alle Mura',
 'Sorrento',
 'Moneglia',
 'Amalfi',
 'Strongoli',
 'Collepietra',
 'Vigano',
 "Isola d'Asti",
 'Civitella Casanova',
 "Villa d'Almè",
 'Olgiate Olona',
 'Badiola',
 'Ostuni',
 'Quarto',
 'Parma',
 'Tavarnelle Val di Pesa',
 'Ravello',
 'Brixen',
 'Forte dei Marmi',
 'Tamion',
 "Sant' Agnello",
 'Porto Cervo',
 'Pennabilli',
 'San Pietro in Cariano',
 'Rubiera',
 'Mazzorbo',
 'Lecce',
 'Acqui Terme',
 'Castelnuovo Berardenga',
 'Cavernago',
 'Catanzaro',
 'Como',
 'Genazzano',
 'Lamporecchio',
 'Pinerolo',
 'Romagnano',
 'Lacco Ameno',
 'Aosta',
 'Ticciano',
 'Norcia',
 'Polesine Parmense',
 'Trani',
 'Capri',
 'Massa Lubrense',
 'Positano',
 'Scorzè',
 'San Quirino',
 'Bergamo',
 'Novara',
 'Dolegna del Collio',
 'Borgonovo Val Tidone',
 'Pontinia',
 'San Giovanni in Fiore',
 'Genoa',
 'Bolzano',
 "Cortina d'Ampezzo",
 'Rimini',
 "Castiglione d'Orcia",
 "Pieve d'Alpago",
 'Baschi',
 'Fagnano Olona',
 'Cagliari',
 'Carovigno',
 'Lavello',
 'Pompei',
 'Manduria',
 'Naples',
 'Matera',
 'Santo Stefano Belbo',
 'Bologna',
 "Monforte d'Alba",
 'Ponza',
 'Noli',
 'Turin',
 'Modica',
 'Selva di Val Gardena',
 'Pesaro',
 'Salerno',
 'Marlia',
 'Lucca',
 'Asiago',
 'Cavalese',
 'Catania',
 'Prague',
 'Atherton',
 'Saratoga',
 'Burlingame',
 'Woodside',
 'Encino',
 'San Jose',
 'Napa',
 'Rutherford',
 'Redwood City',
 'Mountain View',
 'Los Alamos',
 'Paso Robles',
 'San Anselmo',
 'Manhattan Beach',
 'Temple City',
 'Carlsbad',
 'San Mateo',
 'Santa Barbara',
 'Beverly Hills',
 'Carmel-by-the-Sea',
 'Menlo Park',
 'Sacramento',
 'Costa Mesa',
 'Palo Alto',
 'Zgornja Kungota',
 'Nova Gorica',
 'Vipava',
 'Horjul',
 'Ljubljana',
 'Växjö',
 'Borgholm',
 'Tvååker',
 'Gothenburg',
 'Lindesnes',
 'Trondheim',
 'Bergen',
 'Reykjavík',
 'Helsinki',
 'Fredericia',
 'Hørve',
 'Vejle',
 'Åkirkeby',
 'Præstø',
 'Sønderborg',
 'Aarhus',
 'Novalja',
 'Lovran',
 'Rijeka',
 'Rovinj',
 'Sibenik',
 'Zagreb',
 'Mali Lošinj',
 'Korcula',
 'Dubrovnik',
 'Budapest',
 "'s-Hertogenbosch",
 'Aduard',
 'Eindhoven',
 'Wilhelminadorp',
 'Venlo',
 'Well',
 'Haarlem',
 'Monnickendam',
 'Duiven',
 'Noordeloos',
 'Sint-Oedenrode',
 'Blokzijl',
 'Maastricht',
 'Breda',
 'Warmond',
 'Nijmegen',
 'Helmond',
 'Bergambacht',
 'Holten',
 'Heelsum',
 'Beetsterzwaag',
 'Leuvenum',
 'Leersum',
 'Wouw',
 'Capelle aan den IJssel',
 'Schoorl',
 'Tilburg',
 'Bennekom',
 'The Hague',
 'Vreeland',
 'Breskens',
 'Maasbracht',
 'Houten',
 'Hengelo',
 'Willemstad',
 'Linschoten',
 ...]

These are all 'city states' or principalities.

In [16]:
# Create a dictionary for special cases
special_cases = {'Hong Kong': 'Hong Kong, Hong Kong SAR China',
                 'Macau': 'Macau, Macau SAR China',
                 'Singapore': 'Singapore, Singapore',
                 'Dubai': 'Dubai, United Arab Emirates',
                 'Luxembourg': 'Luxembourg, Luxembourg',
                 'Abu Dhabi': 'Abu Dhabi, United Arab Emirates'}

In [17]:
# Apply special cases to the 'location' column
michelin['location'] = michelin['location'].replace(special_cases)

# Now split the 'location' column
locations = michelin['location'].str.split(',', expand=True)
locations.columns = ['city', 'country']

# Remove leading or trailing whitespace from 'city' and 'country' columns
locations['city'] = locations['city'].str.strip()
locations['country'] = locations['country'].str.strip()

# Replace the original 'location' column with the new 'country' and 'city' columns
michelin = michelin.drop('location', axis=1).join(locations)

In [18]:
print(f"New Columns: {michelin.columns.tolist()}")

New Columns: ['name', 'address', 'price', 'currency', 'cuisine', 'url', 'award', 'longitude', 'latitude', 'city', 'country']

In [19]:
print(f"Unique Countries: {michelin['country'].unique()}"
      f"\nTotal Unique = {len(michelin['country'].unique())} values")

Unique Countries: [None 'Macau SAR China' 'Hong Kong SAR China' 'Singapore' 'Luxembourg']
Total Unique = 5 values

In [20]:
print(f"Unique Cities: {michelin['city'].unique()}"
      f"\nTotal Unique = {len(michelin['city'].unique())} values")

Unique Cities: ['Wolfsburg' 'Hamburg' 'Rottach-Egern' ... 'Sint-Truiden' 'Eynatten'
 'Warsaw']
Total Unique = 2716 values

In [21]:
michelin = michelin[['name', 'address', 'city', 'country', 'price', 'cuisine', 'url', 'award', 'longitude', 'latitude']]
michelin.head()

,name,address,city,country,price,cuisine,url,award,longitude,latitude
0,Aqua,"Parkstraße 1, Wolfsburg, 38440, Germany",Wolfsburg,None,225,"Creative, Modern Cuisine",http://www.restaurant-aqua.com,3 MICHELIN Stars,10.789999,52.433172
1,The Table Kevin Fehling,"Shanghaiallee 15, Hamburg, 20457, Germany",Hamburg,None,230,Creative,http://www.the-table-hamburg.de/,3 MICHELIN Stars,10.002980,53.542623
2,Restaurant Überfahrt Christian Jürgens,"Überfahrtstraße 10, Rottach-Egern, 83700, Germany",Rottach-Egern,None,319,Creative,http://www.althoffcollection.com,3 MICHELIN Stars,11.758229,47.696685
3,Victor's Fine Dining by christian bau,"Schlossstraße 27, Perl, 66706, Germany",Perl,None,295,Creative,https://www.victors-fine-dining.de/,3 MICHELIN Stars,6.387211,49.535173
4,Rutz,"Chausseestraße 8, Berlin, 10115, Germany",Berlin,None,245,"Modern Cuisine, Creative",https://www.rutz-restaurant.de/,3 MICHELIN Stars,13.386087,52.528351

----

## `awards` columns

In the Michelin dataset, we have a column named 'awards' that designates the level of recognition a restaurant has achieved according to Michelin's rating system. These awards are '3 MICHELIN Stars', '2 MICHELIN Stars', '1 MICHELIN Star', and 'Bib Gourmand', which is a different award for good quality, good value restaurants.

However, in order to make the analysis more tractable and to create a more uniform scale, we transform these awards into numerical values. This transformation will allow us to perform quantitative analysis and make mathematical computations with this data, which wouldn't be possible with the original textual data.

The '3 MICHELIN Stars', '2 MICHELIN Stars', and '1 MICHELIN Star' awards are straightforwardly transformed into the numerical values 3, 2, and 1, respectively. However, the 'Bib Gourmand' award doesn't fit directly into this star system. In consideration of the prestige and value attached to this award, we've decided to map 'Bib Gourmand' to the value 0.5. It's important to note that this decision, while somewhat arbitrary, is made with the understanding that the 'Bib Gourmand' recognizes a different aspect of restaurant quality and is not strictly comparable to the star awards.

In [16]:
award_dict = {'3 MICHELIN Stars': 3, '2 MICHELIN Stars': 2, '1 MICHELIN Star': 1, 'Bib Gourmand': 0.5}
michelin['stars'] = michelin['award'].replace(award_dict)

In [17]:
cols = michelin.columns.tolist()

cols.remove('stars')
# insert 'stars' at the desired position next to 'award' which we retain
cols.insert(-2, 'stars')

# reindex the DataFrame
michelin = michelin.reindex(columns=cols)

In [18]:
michelin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6832 entries, 0 to 6831
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       6832 non-null   object
 1   address    6832 non-null   object
 2   city       6832 non-null   object
 3   country    6832 non-null   object
 4   price      6783 non-null   object
 5   cuisine    6832 non-null   object
 6   url        5557 non-null   object
 7   award      6832 non-null   object
 8   stars      6832 non-null   float64
 9   longitude  6832 non-null   float64
 10  latitude   6832 non-null   float64
dtypes: float64(3), object(8)
memory usage: 587.2+ KB

----
&nbsp;
## `price` column

There is also the price column to organise which lists a number of different currencies. It is unclear if, for example, $ refers to USD, HKD etc..

This attribute is easier to deal with piecewise by country

----
&nbsp;
## Export `UK` and `France` datasets for further analysis

In [19]:
# Filter the DataFrame for records where country == 'UK'
uk_data = michelin[michelin['country'] == 'United Kingdom']
uk_data.head()

,name,address,city,country,price,cuisine,url,award,stars,longitude,latitude
25,Sketch (The Lecture Room & Library),"9 Conduit Street, London, W1S 2XG, United Kingdom",London,United Kingdom,££££,Modern French,https://sketch.london/,3 MICHELIN Stars,3.0,-0.141537,51.512678
26,L'Enclume,"Cavendish Street, Cartmel, LA11 6PZ, United Ki...",Cartmel,United Kingdom,££££,Creative British,https://www.lenclume.co.uk/,3 MICHELIN Stars,3.0,-2.953857,54.201725
27,Alain Ducasse at The Dorchester,"Park Lane, London, W1K 1QA, United Kingdom",London,United Kingdom,££££,French,https://www.alainducasse-dorchester.com/,3 MICHELIN Stars,3.0,-0.152575,51.507338
28,Hélène Darroze at The Connaught,"Carlos Place, London, W1K 2AL, United Kingdom",London,United Kingdom,££££,Modern Cuisine,https://www.the-connaught.co.uk/restaurants-ba...,3 MICHELIN Stars,3.0,-0.149290,51.510188
29,Fat Duck,"High Street, Bray, SL6 2AQ, United Kingdom",Bray,United Kingdom,££££,Creative,https://thefatduck.co.uk/,3 MICHELIN Stars,3.0,-0.701753,51.507858

In [20]:
# Export the UK data to a csv file
uk_data.to_csv('../data/UK/uk_data.csv', index=False)

In [19]:
# Filter the DataFrame for records where country == 'France'
france_data = michelin[michelin['country'] == 'France']
france_data.head()

,name,address,city,country,price,cuisine,url,award,stars,longitude,latitude
36,La Vague d'Or - Cheval Blanc St-Tropez,"Plage de la Bouillabaisse, Saint-Tropez, 83990...",Saint-Tropez,France,€€€€,"Creative, Modern Cuisine",https://www.chevalblanc.com/fr/maison/st-tropez/,3 MICHELIN Stars,3.0,6.626154,43.266585
37,René et Maxime Meilleur,"Hameau de Saint-Marcel, Saint-Martin-de-Belle...",Saint-Martin-de-Belleville,France,€€€€,"Creative, Regional Cuisine",https://www.la-bouitte.com/fr/,3 MICHELIN Stars,3.0,6.513306,45.369046
38,Kei,"5 rue du Coq-Héron, Paris, 75001, France",Paris,France,€€€€,"Modern Cuisine, Creative",https://www.restaurant-kei.fr/,3 MICHELIN Stars,3.0,2.342285,48.864395
39,Auberge du Vieux Puits,"5 avenue Saint-Victor, Fontjoncouse, 11360, Fr...",Fontjoncouse,France,€€€€,Creative,https://www.aubergeduvieuxpuits.fr/fr/,3 MICHELIN Stars,3.0,2.789329,43.048173
40,Régis et Jacques Marcon,"Larsiallas, Saint-Bonnet-le-Froid, 43290, France",Saint-Bonnet-le-Froid,France,€€€€,Creative,https://www.lesmaisonsmarcon.fr/,3 MICHELIN Stars,3.0,4.434268,45.138673

In [20]:
monaco = france_data[france_data['city'] == 'Monaco']
monaco

,name,address,city,country,price,cuisine,url,award,stars,longitude,latitude
52,Le Louis XV - Alain Ducasse à l'Hôtel de Paris,"Place du Casino, Monaco, 98000, France",Monaco,France,€€€€,"Mediterranean Cuisine, Modern Cuisine",https://www.ducasse-paris.com/,3 MICHELIN Stars,3.0,7.427105,43.739184
342,Le Blue Bay,"40 avenue Princesse-Grace, Monaco, 98000, France",Monaco,France,€€€€,Creative,https://www.montecarlosbm.com/fr/restaurant-mo...,2 MICHELIN Stars,2.0,7.437975,43.748897
1792,Le Grill,"Place du Casino, Monaco, 98000, France",Monaco,France,€€€€,Classic Cuisine,https://www.montecarlosbm.com/fr/restaurant-mo...,1 MICHELIN Star,1.0,7.427100,43.739367
1809,Yoshi,"4 avenue de la Madone, Monaco, 98000, France",Monaco,France,€€€€,Japanese,http://www.metropole.com/fr,1 MICHELIN Star,1.0,7.427975,43.740818
1838,"Pavyllon, un restaurant de Yannick Alléno, Mon...","Square Beaumarchais, Monaco, 98000, France",Monaco,France,€€€€,"Modern Cuisine, Creative",https://www.montecarlosbm.com/fr,1 MICHELIN Star,1.0,7.425868,43.738462
1872,La Table d'Antonio Salvatore au Rampoldi,"3 avenue des Spélugues, Monaco, 98000, France",Monaco,France,€€€€,"Italian, Creative",http://www.rampoldi.mc/la-table-dantonio-salva...,1 MICHELIN Star,1.0,7.427820,43.740456

We remove Monaco from metropolitan France

In [21]:
france_data = france_data[france_data['city'] != 'Monaco']
france_data.shape

(1033, 11)

In [23]:
# Export the France data to a csv file
france_data.to_csv('../data/France/france_master.csv', index=False)

----
&nbsp;
## Restaurants could be further partitioned by country from this point